---
title: "Hoe zit het nou met de COVID gevallen op Curacao?"
output: html_notebook
---

## De data

Om dit te bekijken analyseer ik de [COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University](https://github.com/CSSEGISandData/COVID-19) -- een geweldig voorbeeld van open data!

Ik load hier de data, voor meer instructies zie ook [deze tutorial](https://mdl.library.utoronto.ca/technology/tutorials/covid-19-data-r):
```{r}
confirmedraw <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
deathsraw <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")
recoveredraw <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")
```
We hebben nu de 'raw' data geload. Die moeten we converten naar data die bruikbaar is in R:
```{r}
library(tidyr)
library(dplyr)
confirmed <- pivot_longer(confirmedraw, cols= -c(Country.Region, Province.State, Lat, Long), names_to = "date", values_to = "confirmed")
deaths <- pivot_longer(deathsraw, cols= -c(Country.Region, Province.State, Lat, Long), names_to = "date", values_to = "deaths")
recovered <- pivot_longer(recoveredraw, cols= -c(Country.Region, Province.State, Lat, Long), names_to = "date", values_to = "recovered")

```

```{r}
COVID_data <- full_join(confirmed, deaths) %>%
  full_join(recovered)

COVID_data$date <- COVID_data$date %>% sub("X", "", .) %>% as.Date("%m.%d.%y")

COVID_data <- COVID_data %>%
  group_by(Province.State,Country.Region) %>%
  mutate(
    confirmed.daily = confirmed - lag(confirmed),
    deaths.daily = deaths - lag(deaths),
    recovered.daily = recovered - lag(recovered))

COVID_data$Province.State <- as.factor(COVID_data$Province.State) 
# str(COVID_data)
```

```{r}
library(ggplot2)
COVID_data %>% 
  filter(Province.State %in% c("Aruba","Curacao","Bonaire, Sint Eustatius and Saba", "Sint Maarten")) %>%
  ggplot(aes(x=date, y=confirmed.daily,
             group = Province.State,
             color = Province.State)) +
  geom_line() +
  scale_x_date(limits = as.Date(c("2020-10-01", "2020-12-07"))) +
  # coord_x_date(xlim = c("2020-10-01", "2020-12-07"), ylim = NULL, expand = TRUE) +
  theme_classic() +
  labs(title = "Covid-19 Confirmed Cases Curacao", x= "Date", y= "Daily confirmed cases") +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
COVID_data %>% 
  filter(Province.State %in% c("Aruba","Curacao","Bonaire, Sint Eustatius and Saba", "Sint Maarten")) %>%
  ggplot(aes(x=date,
             group = Province.State,
             color = Province.State)) +
  geom_line(aes(y=confirmed.daily - recovered.daily)) +
  # geom_line(aes(y=recovered.daily), linetype = 'dotted') +
  ylim(-150,150)+
  scale_x_date(limits = as.Date(c("2020-10-01", "2020-12-07"))) +
  # coord_x_date(xlim = c("2020-10-01", "2020-12-07"), ylim = NULL, expand = TRUE) +
  theme_classic() +
  labs(title = "Covid-19 Confirmed-recovered Cases", x= "Date", y= "Daily cases")
  # theme(plot.title = element_text(hjust = 0.5))

```

```{r}
COVID_data %>% 
  filter(Province.State %in% c("Aruba","Curacao","Bonaire, Sint Eustatius and Saba", "Sint Maarten")) %>%
  ggplot(aes(x=date,
             group = Province.State,
             color = Province.State)) +
  geom_line(aes(y=confirmed.daily - recovered.daily)) +
  # geom_line(aes(y=recovered.daily), linetype = 'dotted') +
  ylim(-150,150)+
  # scale_x_date(limits = as.Date(c("2020-10-01", "2020-12-07"))) +
  # coord_x_date(xlim = c("2020-10-01", "2020-12-07"), ylim = NULL, expand = TRUE) +
  theme_classic() +
  labs(title = "Covid-19 Confirmed-recovered Cases", x= "Date", y= "Daily cases")
  # theme(plot.title = element_text(hjust = 0.5))

```

```{r}
library(ggplot2)
COVID_data %>% 
  filter(Province.State %in% c("Aruba","Curacao","Bonaire, Sint Eustatius and Saba", "Sint Maarten")) %>%
  ggplot(aes(x=date, y=recovered.daily,
             group = Province.State,
             color = Province.State)) +
  geom_line() +
  scale_x_date(limits = as.Date(c("2020-10-01", "2020-12-07"))) +
  ylim(0,170)+
  # coord_x_date(xlim = c("2020-10-01", "2020-12-07"), ylim = NULL, expand = TRUE) +
  theme_classic() +
  labs(title = "Covid-19 Recovered Cases Curacao", x= "Date", y= "Daily recovered cases") +
  theme(plot.title = element_text(hjust = 0.5))
```
## older
```{r}
covid19_confirmed_global <- read.csv('csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv')
covid19_recovered_global <- read.csv('csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv')
```

```{r}
covid19_confirmed_global_curacao <- covid19_confirmed_global[covid19_confirmed_global$Province.State=='Curacao',5:length(covid19_confirmed_global$Province.State=='Curacao')]
date = seq(as.Date("2020/1/20"), by = "day", length.out = length(covid19_confirmed_global_curacao))
str(unlist(covid19_confirmed_global_curacao))
str(date)
plot(date,unlist(covid19_confirmed_global_curacao))
```

